# Resolve only the downloaded dependency. An explicit SDK or a local source
# tree never goes through this function and cannot be replaced by a Git fetch.
function(sos_resolve_engine_revision requested_revision lock_file out_revision)
    if(requested_revision STREQUAL "")
        message(FATAL_ERROR "SOS_ENGINE_REVISION must not be empty")
    endif()
    if(NOT requested_revision STREQUAL "locked")
        set(${out_revision} "${requested_revision}" PARENT_SCOPE)
        return()
    endif()

    if(NOT EXISTS "${lock_file}")
        message(FATAL_ERROR "engine.lock is required for SOS_ENGINE_REVISION=locked")
    endif()
    file(STRINGS "${lock_file}" lock_lines)
    set(lock_revisions)
    foreach(line IN LISTS lock_lines)
        string(STRIP "${line}" line)
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        string(LENGTH "${line}" revision_length)
        if(NOT revision_length EQUAL 40 OR NOT line MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "engine.lock must hold exactly one 40-character laiue commit SHA")
        endif()
        list(APPEND lock_revisions "${line}")
    endforeach()
    list(LENGTH lock_revisions revision_count)
    if(NOT revision_count EQUAL 1)
        message(FATAL_ERROR "engine.lock must hold exactly one 40-character laiue commit SHA")
    endif()
    list(GET lock_revisions 0 revision)
    set(${out_revision} "${revision}" PARENT_SCOPE)
endfunction()
